version: '3'
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    command: java -jar your-java-app.jar

networks:
  default:
    driver: bridge